### ISSUE TITLE
性能瓶颈检测-成刚

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/SysPerfOpt2019#4]
性能异常检测，paper survey及系统实验尝试。

**Comment by ACA-Lab-SJTU** [comment]
成刚，有何更新？

**Comment by dbshch** [comment]
看了一篇OSDI18上的”wPerf: Generic Off-CPU Analysis to Identify Bottleneck Waiting Events“和一些相关内容，不知是否切题

**Comment by ACA-Lab-SJTU** [comment]
看题目还是相关的。请在markdown上写好阅读笔记和问题。我们组会讨论。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by ACA-Lab-SJTU** [comment]
成刚：
- LLP-tests，kernel更新带来多少性能提升；
- 设置测试的configuration，核心数量，限制内存、缓存、swap机制
- 对所有配置进行排列组合和自动化测试
